### ISSUE TITLE
Add a CLI config populator

### ISSUE THREAD

**Issue by solher** [zpatrick/go-config#3]
I absolutely love the fact that your library is CLI friendly as I am a big fan of that tool.

The only thing is that it seems that you only allow to set CLI as a provider. CLI being more than just a flag parser, if think a lot of users will be annoyed by the fact that they have to switch to a "go-config centered" system with CLI being the provider.
I'd love to have a feature to allow go-config to be a provider for CLI.

For example, I'd like to have the following behaviour.
`./app -option "foobar"` -> The option flag is set.
`./app -option "foobar" -config "config.yaml"` -> The option flag is overriden if an `option` value is set in the config file.

In use, it would be something like that:

``` go
func initConfig() *config.Config {
    yamlFile := config.NewYAMLFile("config.yaml")
    return config.NewConfig([]config.Provider{yamlFile})
}

func main() {
    conf := initConfig()

    app := cli.NewApp()
    app.Flags = []cli.Flag{
        cli.StringFlag{
            Name:  "message",
            Value: "Hello from main.go",
            Usage: "Message to print",
        },
        cli.BoolFlag{
            Name: "silent",
            Usage: "Don't print the message",
        },
    }

    app.Action = func(c *cli.Context) {
        config.SetCLI(c)
        // The rest of the app where we get CLI vars
    }

    app.Run(os.Args)
}
```

Or maybe it is already possible or other tools can do that.

**Comment by zpatrick** [comment]
Hi Solher,

Thanks for the idea! I think this would be really cool to implement. I'll give it an honest effort and see what I come up with. Feel free to pitch any other ideas/features you think would be valuable.

Thanks,
Zack

**Comment by solher** [comment]
No problem. Thanks ;)

**Comment by solher** [comment]
Hey, any news ?
I have a project right now where I'd love to have that feature :)

**Comment by zpatrick** [comment]
Hi Solher,

My original approach to implementing this was to set the values of flags if they weren't already present during `config.SetCLI(c)`. However, I don't think there is a way to do this with the current `cli` code. For reference, I checked:
- [cli/context](https://github.com/codegangsta/cli/blob/master/context.go)
- [cli/app](https://github.com/codegangsta/cli/blob/master/app.go)
- [cli/command](https://github.com/codegangsta/cli/blob/master/command.go)

On the bright side, there are a couple of open merge requests/issues that are related:
- [Allow context value to be set after parse](https://github.com/codegangsta/cli/pull/234)
- [Config integration](https://github.com/codegangsta/cli/issues/235)
- [Add ability to get global and command level variables from a yaml file](https://github.com/codegangsta/cli/issues/301)

The other approaches I came up with had some flaws:

##### Approach 2

Wrap `*cli.Context` with my own object. Keep the same function signatures, but perform lookups from `config` before caling the original lookup function(s). The problem I had was that the code would end up looking like this:

```
    app.Action = func(c *cli.Context) {
        ctx := config.SetCLI(c)

        message := ctx.String("message")
        ...
```

Compared to what is already available: 

```
    app.Action = func(c *cli.Context) {
        conf.Providers = append(conf.Providers, config.NewCLI(c, false))

        message, err := conf.String("message")
        if err != nil {
            ...
```

Aside from providing very similar usage, it kind of ruined the central purpose of your feature request, which was to keep the code "cli centered". Really, the only missing parts between the existing `config` pattern and the `*cli.Context` is the `arg` lookup/helper functions, and the `Duration` type. If you were dead-set on using only one object for this, you could probably wrap a `*config.Config` and `*cli.Context` in a struct pretty easily: 

```
type ConfigContext struct{
    config *config.Config
    *cli.Context
}

func (this *ConfigContext) String(key string) (string, error){
    val, err := this.config.StringOr(key, "")
    if err != nil{
        return "", err
    }

    if val != "" {
        return val
    }

    return this.context.String(key), nil
}

// you can use ConfigContext.Args() same way you would a *cli.Context
```

##### Approach 3

 Leverage the fact that all of the flags sent to a `cli.Command` are interfaces. Create wrappers around the flag structs that performed some config lookups before populating their value. Again, the main problem I had with this is that it would make a lot of your code `config` centered instead of `cli` centered. Also, having to map each flag to a particular key/inject each flag with the `Config` object seemed pretty messy. It also wouldn't allow for the behavior you wanted: "if x, then use config for lookups" - this approach would force config lookups to always be performed. 

##### Approach 4

 Instead of running  `app.Run(os.Args)`, perform some logic around `os.Args` to allow custom flag values to be injected. This is obviously a terrible idea for a lot of reasons, so I won't go into detail there. 

So anyways, unless there is a major approach that I missed (please let me know if there is!), I think the best step moving forward is to wait for one of the merge requests mentioned above to get merged. In the mean time, despite the alternate solution(s) stated above, I think updating your code to use the `config` object for flag lookups is probably the quickest and cleanest solution available at the moment. 

I'll keep this issue open, an eye on those merge requests, and update this thread if it becomes feasible to build this feature. 

-Zack

**Comment by solher** [comment]
Awesome work !
You're totally right, I think the best thing to do is to wait for CLI to directly support conf files.
(To be fair, I didn't even check the CLI pull requests about the idea...)
But thanks for giving it a shot !

**Comment by zpatrick** [comment]
closing as https://github.com/urfave/cli#values-from-files is a supported option.
